Feat/partial update with sign
jkugiya/elastic-scala-httpclient pull request #1
Opened 2016-11-25 13:38 UTC by chaabaj

2016-11-29 06:54 UTC, jkugiya requested changes

2016-11-29 06:54 UTC, jkugiya commented on elastic-scala-httpclient/src/main/scala/jp/co/bizreach/elasticsearch4s/AsyncESClient.scala
> +    logger.debug(s"insertJson:\n$json")
Please don't change unrelated code.

2016-11-29 06:54 UTC, jkugiya commented on elastic-scala-httpclient/src/main/scala/jp/co/bizreach/elasticsearch4s/AsyncESClient.scala
> +    logger.debug(s"insertJson:\n$json")
Please don't change existing code format.

2016-11-30 00:58 UTC, merged

2016-11-30 10:04 UTC, chaabaj commented on elastic-scala-httpclient/src/main/scala/jp/co/bizreach/elasticsearch4s/AsyncESClient.scala
> +    logger.debug(s"insertJson:\n$json")
it was just fixing warning from ide i will revert it